[app]
ns="EcsCICDDemo"
stage="Dev"

[aws]
region="ap-northeast-2"

[service.echo]
name="http-echo"
port=8090
codeRepositoryName="http-echo"
ecrRepositoryName="http-echo"

[user]
myip="127.0.0.1/32"

# [notification]
# slackHookUrl=""